### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by armills** [Maxr1998/home-assistant-Android#19]
Stack trace attached. It also included some of the hass state data, but looks like it was truncated. This should hopefully help track it down, though. Using version 0.2 from F-Droid.

```
D/HassService( 6934): 3: {"id":3,"success":true,"type":"result","result":[{"state":"on","entity_id":"group.automation_lights","last_updated":"2017-04-18T12:00:05.849019+00:00","last_changed":"2017-04-18T12:00:05.849019+00:00","attributes":{"friendly_name":"Bird Room","entity_id":["light.bird_room_level_6_0"],"order":3}},{"state":"on","entity_id":"automation.suspend_kodi_after_inactivity","last_updated":"2017-04-16T18:04:26.605838+00:00","last_changed":"2017-04-16T18:04:26.605838+00:00","attributes":{"friendly_name":"Suspend Kodi after inactivity","hidden":true,"last_triggered":null}},{"state":"on","entity_id":"light.zwave_micro_dimmer_level_5_0","last_updated":"2017-04-16T18:04:26.840153+00:00","last_changed":"2017-04-16T18:04:26.840153+00:00","attributes":{"friendly_name":"Zwave Micro Dimmer Level","supported_features":33,"brightness":70,"node_id":5}},{"state":"on","entity_id":"automation.flic_all_lights_off","last_updated":"2017-04-16T18:04:26.590318+00:00","last_changed":"2017-04-16T18:04:26.590318+00:00","attributes":{"friendly_name":"Flic All Lights Off","hidden":true,"last_triggered":null}},{"state":"on","entity_id":"light.living_room_floor","last_updated":"2017-04-18T21:38:16.975720+00:00","last_changed":"2017-04-18T21:37:48.807452+00:00","attributes":{"xy_color":[0.4347,0.4032],"friendly_name":"Living Room Floor","color_temp":328,"effect_list":["colorloop","random"],"supported_features":127,"brightness":254,"rgb_color":[255,215,139]}},{"state":"off","entity_id":"switch.kodi_pc","last_updated":"2017-04-16T18:04:19.202474+00:00","last_changed":"2017-04-16T18:04:19.202474+00:00","attributes":{"friendly_name":"Kodi PC"}},{"state":"on","entity_id":"automation.finish_party_mode","last_updated":"2017-04-16T18:04:26.592102+00:00","last_changed":"2017-04-16T18:04:26.592102+00:00","attributes":{"friendly_name":"Finish Party Mode","hidden":true,"last_triggered":null}},{"state":"off","entity_id":"media_player.upstairs_bedroom","last_updated":"2017-04-17T03:07:30.765914+00:00","last_changed":"2017-04-17T03:07:30.765914+00:00","attributes":{"friendly_name":"Upstairs Bedroom","supported_features":21437}},{"state":"off","entity_id":"input_boolean.activate_snapcast_chromecast","last_updated":"2017-04-16T18:04:16.093998+00:00","last_changed":"2017-04-16T18:04:16.093998+00:00","attributes":{}},{"state":"closed","entity_id":"group.garage_door","last_updated":"2017-04-18T03:18:41.051336+00:00","last_changed":"2017-04-18T03:18:41.051336+00:00","attributes":{"friendly_name":"Garage Door","entity_id":["cover.garage_door__7_0"],"order":4}},{"state":"on","entity_id":"automation.finish_snapcast","last_updated":"2017-04-16T18:04:26.595372+00:00","last_changed":"2017-04-16T18:04:26.595372+00:00","attributes":{"friendly_name":"Finish Snapcast","hidden":true,"last_triggered":null}},{"state":"Ready","entity_id":"zwave.controller_1","last_updated":"2017-04-16T18:04:35.267655+00:00","last_changed":"2017-04-16T18:04:35.267655+00:00","attributes":{"friendly_name":"Controller","query_stage":"Complete","neighbors":[8,3,5,6],"is_ready":true,"is_zwave_plus":false,"capabilities":["listening","primaryController","beaming"],"is_info_received":true,"node_id":1,"is_failed":false,"is_awake":true,"max_baud_rate":40000}},{"state":"on","entity_id":"automation.suspend_kodi_when_chromecast_active","last_updated":"2017-04-18T02:28:30.917592+00:00","last_changed":"2017-04-16T18:04:26.607493+00:00","attributes":{"friendly_name":"Suspend Kodi when Chromecast active","hidden":true,"last_triggered":"2017-04-18T02:28:30.917394+00:00"}},{"state":"on","entity_id":"automation.dim_bedroom_light_for_tv_time","last_updated":"2017-04-17T02:33:56.008071+00:00","last_changed":"2017-04-16T18:04:26.612766+00:00","attributes":{"friendly_name":"Dim bedroom light for TV time","last_triggered":"2017-04-17T02:33:56.007911+00:00"}},{"state":"on","entity_id":"automation.turn_on_bedroom_light_at_night","last_updated":"2017-04-17T23:33:35.016062+00:00","last_changed":"2017-04-16T18:04:26.627735+00:00","attributes":{"friendly_name":"Turn on bedroom light at night","last_triggere
E/HassService( 6934): Error in onMessage()
E/HassService( 6934): java.lang.IllegalArgumentException: Invalid primitive conversion from double to int
E/HassService( 6934): at java.lang.reflect.Field.set(Native Method)
E/HassService( 6934): at com.afollestad.ason.Util.setFieldValue(Util.java:230)
E/HassService( 6934): at com.afollestad.ason.ClassCacheEntry.set(ClassCacheEntry.java:63)
E/HassService( 6934): at com.afollestad.ason.AsonSerializer.deserialize(AsonSerializer.java:168)
E/HassService( 6934): at com.afollestad.ason.AsonSerializer.deserialize(AsonSerializer.java:180)
E/HassService( 6934): at com.afollestad.ason.Ason.deserialize(Ason.java:388)
E/HassService( 6934): at io.homeassistant.android.api.HassUtils.extractEntitiesFromStateResult(HassUtils.java:32)
E/HassService( 6934): at io.homeassistant.android.HassService$1.onRequestResult(HassService.java:153)
E/HassService( 6934): at io.homeassistant.android.HassService$HassSocketListener.onMessage(HassService.java:227)
E/HassService( 6934): at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
E/HassService( 6934): at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
E/HassService( 6934): at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
E/HassService( 6934): at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
E/HassService( 6934): at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
E/HassService( 6934): at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
E/HassService( 6934): at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/HassService( 6934): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/HassService( 6934): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/HassService( 6934): at java.lang.Thread.run(Thread.java:818)
```

**Comment by Maxr1998** [comment]
Which apk did you use? The one from GitHub or a newer one from gitter? It seems that the JSON data has a `double` for either `attributes.order` or `attributes.supported_features` for one of the entities. Could you find out which one from the dev states?

**Comment by armills** [comment]
I edited my post to include it, I'm using version 0.2 built on F-Droid: https://f-droid.org/wiki/page/io.homeassistant.android

If this has since been fixed feel free to ignore, just wanted to provide the info if it's helpful. I didn't see any entity that has a float in those fields.

**Comment by armills** [comment]
Pasted current states (GPS redacted) if you want to try it yourself.

https://pastebin.com/YB6vXkWi

**Comment by Maxr1998** [comment]
I believe I found the issue, the brightness value is also an int in my code.. and both in your states are doubles. Will fix this bug in a minute and send you a test apk.

**Comment by armills** [comment]
Interesting. I believe brightness is supposed to be an int, but it looks like the zwave lights are returning a float. It would be good for the app to accept floats, but we should probably also fix it on the zwave side.
